'testbugPR4'

diff --git a/.github/workflows/java-pr-review.yml b/.github/workflows/java-pr-review.yml
--- a/.github/workflows/java-pr-review.yml
+++ b/.github/workflows/java-pr-review.yml
@@ -5,21 +5,21 @@ on:
     types: [opened, synchronize, reopened]
 
 jobs:
-      - name: Debug SpotBugs output
-        run: |
-          echo "SpotBugs XML output (spotbugsXml.xml):"
-          cat target/spotbugsXml.xml || echo "File not found or empty."
   code_review:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up JDK 17
+      - name: Set up JDK 8
         uses: actions/setup-java@v3
+
+      - name: Debug SpotBugs output
+        run: |
+          echo "SpotBugs XML output (spotbugsXml.xml):"
+          cat target/spotbugsXml.xml || echo "File not found or empty."
         with:
-          java-version: '17'
+          java-version: '8'
           distribution: 'temurin'
 
       - name: Install ReviewDog
